const CHANGE_EMAIL_VALUE = "CHANGE_EMAIL_VALUE";
const CHANGE_PASSWORD_VALUE = "CHANGE_PASSWORD_VALUE";
const SHOW_PASSWORD_VALUE = "SHOW_PASSWORD_VALUE";
const CHECK_AUTH = "CHECK_AUTH";
const ADMIN_ID = "2YQ7VK9VjihA5p4bSuQQebDzYuF2";


export { 
    CHANGE_EMAIL_VALUE, 
    CHANGE_PASSWORD_VALUE, 
    SHOW_PASSWORD_VALUE,
    CHECK_AUTH,
    ADMIN_ID };